import { SVGProps } from "react";

export type IconSvgProps = SVGProps<SVGSVGElement> & {
  size?: number;
};

export type ActionResponse<T> = {
  success: boolean;
  message: string;
  fieldErrors?: Record<string, string[]>;
  data?: T;
};
// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserRole = "ADMIN" | "PROJECT_OWNER" | "USER" | "VERIFIER";

export type ProjectType =
  | "MANGROVE"
  | "SEAGRASS"
  | "SALT_MARSH"
  | "CORAL_REEF"
  | "KELP_FOREST";

export type ProjectStatus =
  | "PENDING"
  | "ACTIVE"
  | "APPROVED"
  | "REJECTED"
  | "COMPLETED";

export type ProjectRole = "OWNER" | "MANAGER" | "CONTRIBUTOR" | "VIEWER";

export type CreditStatus = "ACTIVE" | "SOLD" | "RETIRED" | "BURNED";

export type TransactionType =
  | "MINT"
  | "TRANSFER"
  | "PURCHASE"
  | "RETIRE"
  | "BURN";

export type TransactionStatus =
  | "PENDING"
  | "PROCESSING"
  | "COMPLETED"
  | "FAILED";

export type DeviceStatus = "ACTIVE" | "INACTIVE" | "MAINTENANCE" | "ERROR";

export type DeviceType = "SENSOR" | "CAMERA" | "WEATHER_STATION";

export type MeasurementType =
  | "TEMPERATURE"
  | "PH"
  | "SALINITY"
  | "TURBIDITY"
  | "DISSOLVED_OXYGEN"
  | "WATER_LEVEL"
  | "BIOMASS";

export type OrganizationType = "NGO" | "PANCHAYAT" | "COMMUNITY" | "COMPANY";

export interface User {
  id: string;
  name: string | null;
  email: string;
  emailVerified: boolean;
  image: string | null;
  createdAt: Date;
  updatedAt: Date;
  profile?: UserProfile | null;
  sessions?: Session[];
  accounts?: Account[];
  transactions?: Transaction[];
  projects?: ProjectUser[];
}

export interface UserProfile {
  id: string;
  userId: string;
  user?: User;
  role: UserRole;
  walletAddress: string | null;
  organization: string | null;
  country: string | null;
  phoneNumber: string | null;
  bio: string | null;
  totalCreditsEarned: number;
  totalCreditsSold: number;
  totalCreditsBought: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Session {
  id: string;
  userId: string;
  user?: User;
  token: string;
  expiresAt: Date;
  ipAddress: string | null;
  userAgent: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Account {
  id: string;
  userId: string;
  user?: User;
  accountId: string;
  providerId: string;
  accessToken: string | null;
  refreshToken: string | null;
  accessTokenExpiresAt: Date | null;
  refreshTokenExpiresAt: Date | null;
  scope: string | null;
  idToken: string | null;
  password: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface Project {
  id: string;
  organizationName: string;
  organizationType: OrganizationType;
  registrationNumber: string | null;
  contactPerson: string;
  email: string;
  phone: string;
  projectName: string;
  projectDescription: string;
  projectType: ProjectType;
  state: string;
  district: string;
  village: string;
  coordinates: Coordinates;
  totalArea: number;
  estimatedCreditsPerYear: number;
  totalCreditsGenerated: number;
  projectPhotos: ProjectPhoto[];
  hasLegalPermits: boolean;
  hasSurveyReport: boolean;
  hasEnvironmentalClearance: boolean;
  adminNotes?: string;
  verificationNotes?: string;
  contractAddress: string | null;
  tokenId: string | null;
  iotDevices?: IoTDevice[];
  users?: ProjectUser[];
  transactions?: Transaction[];
  measurements?: Measurement[];
  status: ProjectStatus;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProjectUser {
  id: string;
  projectId: string;
  project?: Project;
  userId: string;
  user?: User;
  role: ProjectRole;
  joinedAt: Date;
}

export interface CarbonCredit {
  id: string;
  projectId: string;
  amount: number;
  vintage: number;
  status: CreditStatus;
  blockchainTxHash: string | null;
  mintedAt: Date | null;
  burnedAt: Date | null;
  certificationBody: string | null;
  certificationId: string | null;
  transactions?: Transaction[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Transaction {
  id: string;
  type: TransactionType;
  fromUserId: string | null;
  fromUser?: User | null;
  toUserId: string | null;
  projectId: string | null;
  project?: Project | null;
  creditId: string | null;
  credit?: CarbonCredit | null;
  amount: number;
  pricePerCredit: number | null;
  totalPrice: number | null;
  currency: string;
  txHash: string | null;
  blockNumber: number | null;
  gasUsed: number | null;
  status: TransactionStatus;
  metadata: JsonValue | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface IoTDevice {
  id: string;
  deviceId: string;
  name: string;
  type: DeviceType;
  projectId: string;
  project?: Project;
  status: DeviceStatus;
  lastPing: Date | null;
  measurements?: Measurement[];
  metadata: JsonValue | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Measurement {
  id: string;
  deviceId: string;
  device?: IoTDevice;
  projectId: string;
  project?: Project;
  measurementType: MeasurementType;
  value: number;
  unit: string;
  timestamp: Date;
  metadata: JsonValue | null;
}

type JsonValue =
  | string
  | number
  | boolean
  | { [key in string]?: JsonValue }
  | Array<JsonValue>
  | null;

interface Coordinates {
  lat: number;
  lng: number;
}

export interface ImageUploadResult {
  urls: string[];
  errors: string[];
}

export interface ImageValidation {
  isValid: boolean;
  error?: string;
}

export interface BlockchainState {
  contractAddress: string;
  creditPrice: string;
  ownerCredits: number;
  isConnected: boolean;
  userCredits: number;
}

export interface BlockchainTransaction {
  type: "Generation" | "Purchase" | "Price Update" | "Withdrawal";
  amount?: number;
  txHash: string;
  cost?: string;
  newPrice?: number;
  status: "success" | "pending" | "failed";
  timestamp: Date;
}

export interface WalletState {
  address: string | null;
  isConnected: boolean;
  balance: string;
  credits: number;
}

export interface ProjectPhoto {
  id: string;
  filename: string;
  category: "site-current" | "site-reference" | "documentation";
  description: string;
  url: string;
  size: number;
  uploadDate: string;
}
